name: Publication task

on:
  release:
    types: [published]
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    #- name: Publish (GitHub Packages)
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #    BUILD_NUMBER: 0 # Releases are always major.minor.revision_0
    #  run: ./gradlew publish
    - name: Zip files
      run: |
        cd build
        zip release-${{ github.event.release.tag_name }} *
    - name: Upload to release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.release.upload_url }}
        asset_path: ./build/release-${{ github.event.release.tag_name }}.zip
        asset_name: release-${{ github.event.release.tag_name }}.zip
        asset_content_type: application/zip
